source 'https://rubygems.org'

gem 'coffee-rails', '~> 4.1.0'
gem 'devise', '~> 3.4.1'
gem 'jquery-rails'
gem 'log4r', '~> 1.1'
gem 'omniauth-cas', '~> 1.1.0'
gem 'rabl', '~> 0.11.6'
gem 'rails', '4.2.0'
gem 'rails_admin', '~> 0.6.6'
gem 'sass-rails', '~> 5.0'
gem 'sqlite3'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'
gem 'unicorn', '~> 4.8.3'

group :development, :test do
  gem 'byebug'
  gem 'database_cleaner', '~> 1.4.0'
  gem 'factory_girl', '~> 4.5.0'
  gem 'rspec-rails', '~> 3.1.0'
  gem 'simplecov', '~> 0.9.1'
  gem 'spring'
  gem 'web-console', '~> 2.0'
end
