default: &default
  adapter: <%= Rails.application.secrets['database']['adapter'] %>
  pool: <%= Rails.application.secrets['database']['pool'] %>
  timeout: <%= Rails.application.secrets['database']['timeout'] %>
  database: <%= Rails.application.secrets['database']['name'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
